dist: trusty
services:
  - xvfb
sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
script:
  - yarn test:ci
