language: node_js
node_js:
  - "10"
addons:
  chrome: stable
  apt:
    packages:
      - fluxbox
before_install:
  - stty cols 80
install:
  - yarn
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
script:
  - yarn test:ci
