language: node_js
addons:
  chrome: stable
node_js:
  - "10"
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  # Install npm packages
  - "npm install"
  # Run TestCafe
  - "./node_modules/.bin/testcafe 'chrome --headless --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0' tests/todomvc.spec.ts --skip-js-errors --assertion-timeout 30000"
