name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Start xvfb
        run: |
          sudo apt-get install xvfb
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Install node.js 10
        uses: actions/setup-node@v1
        with:
          version: 10

      - name: Run test
        run: |
          yarn
          yarn test:ci
          npx allure generate .allure/allure-results -o .allure/allure-report --clean

      - name: Archive html report
        uses: actions/upload-artifact@v1
        with:
          name: visual-regression-report
          path: .allure/allure-report
